# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	# boot 
	boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];
	boot.extraModprobeConfig = "options kvm-intel nested=1";

	# filesystem
	boot.zfs.forceImportRoot = true;
	boot.zfs.extraPools = [
		"LunarRepo"
	];

	fileSystems."/" = {
		device = "LunarRoot/NixosRoot";
		fsType = "zfs";
	};

	fileSystems."/.profiles" = {
		device = "LunarRoot/profiles";
		fsType = "zfs";
	};

	fileSystems."/nix" = {
		device = "LunarRoot/Nix";
		fsType = "zfs";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/7843-A749";
		fsType = "vfat";
		options = [ "fmask=0022" "dmask=0022" ];
	};

	swapDevices = [ ];
	networking.hostId = "0c027313";

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

	services.zfs.autoScrub = {
		enable = true;
		interval = "weekly";
	};

	#  services.smartd = {
	# enable = true;
	# devices = [
	# 	{
	# 		device = "/dev/disk/by-uuid/17377484653442125737";
	# 		options = "-a -o on -S on -s (S/../.././02|L/../../7/03)";
	# 	}
	# 	{
	# 		device = "/dev/disk/by-uuid/15075018794702833505";
	# 		options = "-a -o on -S on -s (S/../.././02|L/../../7/03)";
	# 	}
	# 	{
	# 		device = "/dev/disk/by-uuid/14924946931738502554";
	# 		options = "-a -o on -S on -s (S/../.././02|L/../../7/03)";
	# 	}
	# ];
	#  };

}
